// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async beginConnectedImport(providerId: string) : Promise<Result<ConnectedImportAuthorization, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:importer|begin_connected_import", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelConnectedImport(providerId: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:importer|cancel_connected_import", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async completeConnectedImport(providerId: string) : Promise<Result<ConnectedImportCredentials, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:importer|complete_connected_import", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async syncConnectedImport(providerId: string, credentials: ConnectedImportCredentials, knownMeetingIds: string[]) : Promise<Result<ConnectedImportSyncResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:importer|sync_connected_import", { providerId, credentials, knownMeetingIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readTextFiles(paths: string[]) : Promise<Result<ImportTextFile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:importer|read_text_files", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists the immediate children of a user-selected import directory, so the
 * caller can discover sibling export bundles (one folder per meeting)
 * without knowing their names in advance.
 */
async listDirectoryEntries(path: string) : Promise<Result<ImportDirectoryEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:importer|list_directory_entries", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ConnectedImportAuthorization = { providerId: string; authorizationUrl: string }
export type ConnectedImportCredentials = { providerId: string; clientId: string; clientSecret: string | null; tokenJson: string; tokenReceivedAt: number | null }
export type ConnectedImportSyncResult = { files: ImportTextFile[]; credentials: ConnectedImportCredentials; warnings: string[] }
export type ImportDirectoryEntry = { name: string; path: string; isDir: boolean }
export type ImportTextFile = { path: string; name: string; content: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
