[package]
name = "tauri-plugin-tracing"
version = "0.1.0"
authors = ["You"]
edition = "2024"
exclude = ["/js", "/node_modules"]
links = "tauri-plugin-tracing"
description = ""

[build-dependencies]
tauri-plugin = { workspace = true, features = ["build"] }

[dev-dependencies]
dirs = { workspace = true }
rquickjs = "0.10"
sentry = { workspace = true, features = ["tracing"] }
specta-typescript = { workspace = true }
tauri = { workspace = true, features = ["test"] }
tempfile = { workspace = true }
tracing-appender = { version = "0.2" }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[dependencies]
anlg-crash-reporting = { workspace = true }
tauri = { workspace = true }
tauri-specta = { workspace = true, features = ["derive", "typescript"] }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
specta = { workspace = true, features = ["derive", "serde_json"] }

thiserror = { workspace = true }
tracing = { workspace = true }
tracing-appender = { version = "0.2" }
tracing-subscriber = { workspace = true, features = ["env-filter", "chrono"] }
