mod commands;
mod error;
mod ext;
mod manifest;
mod migrate;
#[cfg(target_os = "windows")]
mod windows;

// Tauri unit tests bypass the application manifest while still importing
// TaskDialogIndirect, so the test object must activate Common Controls v6.
#[cfg(all(test, target_os = "windows", target_env = "msvc"))]
#[used]
#[unsafe(link_section = ".drectve")]
static WINDOWS_TEST_MANIFEST_DIRECTIVES: [u8; 184] = *b" /MANIFEST:EMBED /MANIFESTDEPENDENCY:\"type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'\"\0";

pub use anlg_desktop_auth::AccountInfo;
pub use error::{Error, Result};
pub use ext::*;
use tauri::Manager;

const PLUGIN_NAME: &str = "auth";

fn make_specta_builder<R: tauri::Runtime>() -> tauri_specta::Builder<R> {
    tauri_specta::Builder::<R>::new()
        .plugin_name(PLUGIN_NAME)
        .commands(tauri_specta::collect_commands![
            commands::decode_claims,
            commands::get_item::<tauri::Wry>,
            commands::set_item::<tauri::Wry>,
            commands::remove_item::<tauri::Wry>,
            commands::clear::<tauri::Wry>,
            commands::get_account_info::<tauri::Wry>,
        ])
        .typ::<anlg_supabase_auth::Claims>()
        .error_handling(tauri_specta::ErrorHandlingMode::Result)
}

pub fn init<R: tauri::Runtime>() -> tauri::plugin::TauriPlugin<R> {
    let specta_builder = make_specta_builder();

    tauri::plugin::Builder::new(PLUGIN_NAME)
        .invoke_handler(specta_builder.invoke_handler())
        .setup(|app, _api| {
            #[cfg(all(target_os = "linux", not(test)))]
            let auth_store = anlg_supabase_auth::client::store::AuthStore::in_memory(
                migrate::load_linux_auth(app)?,
            );

            #[cfg(all(target_os = "windows", not(test)))]
            let auth_store =
                anlg_supabase_auth::client::store::AuthStore::in_memory(windows::load_auth(app)?);

            #[cfg(any(not(any(target_os = "linux", target_os = "windows")), test))]
            let auth_store = {
                let auth_path = migrate::auth_path(app)?;
                anlg_supabase_auth::client::store::AuthStore::load(auth_path)
            };

            app.manage(auth_store);
            Ok(())
        })
        .build()
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn command_manifest_is_single_source() {
        let mut manifest_commands: Vec<String> = crate::manifest::COMMANDS
            .iter()
            .map(|command| command.to_string())
            .collect();
        manifest_commands.sort_unstable();

        // Export to a private path: export_types rewrites js/bindings.gen.ts
        // concurrently, so reading the shared file here would race with it.
        let bindings_path = std::env::temp_dir().join(format!(
            "anlg-{PLUGIN_NAME}-manifest-sync-{}.ts",
            std::process::id()
        ));
        make_specta_builder::<tauri::Wry>()
            .export(
                specta_typescript::Typescript::default()
                    .bigint(specta_typescript::BigIntExportBehavior::Number),
                &bindings_path,
            )
            .unwrap();
        let bindings = std::fs::read_to_string(&bindings_path).unwrap();
        let _ = std::fs::remove_file(&bindings_path);
        let prefix = format!("plugin:{PLUGIN_NAME}|");
        let mut binding_commands: Vec<String> = bindings
            .split(prefix.as_str())
            .skip(1)
            .filter_map(|rest| rest.split('"').next().map(str::to_string))
            .collect();
        binding_commands.sort_unstable();
        binding_commands.dedup();
        assert_eq!(
            binding_commands, manifest_commands,
            "generated bindings drifted from src/manifest.rs"
        );

        let mut permission_commands: Vec<String> =
            std::fs::read_dir("./permissions/autogenerated/commands")
                .unwrap()
                .map(|entry| entry.unwrap().path())
                .filter(|path| path.extension().is_some_and(|ext| ext == "toml"))
                .filter_map(|path| {
                    path.file_stem()
                        .map(|stem| stem.to_string_lossy().into_owned())
                })
                .collect();
        permission_commands.sort_unstable();
        assert_eq!(
            permission_commands, manifest_commands,
            "generated permissions drifted from src/manifest.rs"
        );
    }

    #[test]
    fn export_types() {
        const OUTPUT_FILE: &str = "./js/bindings.gen.ts";

        make_specta_builder::<tauri::Wry>()
            .export(
                specta_typescript::Typescript::default()
                    .formatter(specta_typescript::formatter::prettier)
                    .bigint(specta_typescript::BigIntExportBehavior::Number),
                OUTPUT_FILE,
            )
            .unwrap();

        let content = std::fs::read_to_string(OUTPUT_FILE).unwrap();
        std::fs::write(OUTPUT_FILE, format!("// @ts-nocheck\n{content}")).unwrap();
    }

    fn create_app<R: tauri::Runtime>(builder: tauri::Builder<R>) -> tauri::App<R> {
        builder
            .plugin(tauri_plugin_settings::init())
            .plugin(init())
            .build(tauri::test::mock_context(tauri::test::noop_assets()))
            .unwrap()
    }

    #[test]
    fn test_auth() {
        let app = create_app(tauri::test::mock_builder());

        let _ = app.set_item("test_key".to_string(), "test_value".to_string());
        let _ = app.get_item("test_key".to_string());
    }
}
