//! Generated from `apps/desktop/src/settings/ai/{stt,llm}/shared.tsx`
//! (`_PROVIDERS` + `PROVIDER_ORDER`) by /tmp/gen_registry.py; keep in sync
//! with the Tauri registries rather than editing by hand.

/// How `ProviderLobeIcon` / `ProviderBrandImage` draw a provider's mark.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Icon {
    /// A multi-colour brand SVG (or bitmap), drawn as an image.
    Image(&'static str),
    /// `getLocalModelIcon`'s `<img>` filling the 20px `AiIconSlot`
    /// (`object-contain`; the NVIDIA wordmark `object-cover object-left`).
    Model(&'static str),
    /// A single-colour glyph: `colorPrimary` unless it is a theme-tinted
    /// colour, in which case the foreground colour is used.
    Mono(&'static str, Option<u32>),
    /// One of the bundled Hugeicons.
    Glyph(&'static str),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Requirement {
    Config(&'static [&'static str]),
    Entitlement(&'static str),
    Auth,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Provider {
    pub id: &'static str,
    pub display_name: &'static str,
    pub badge: Option<&'static str>,
    pub description: Option<&'static str>,
    pub icon: Icon,
    pub base_url: Option<&'static str>,
    /// `new URL(path, env.VITE_API_URL)`: the hosted API.
    pub base_url_is_api: bool,
    pub models: &'static [&'static str],
    pub requirements: &'static [Requirement],
    /// `(kind, label, url)` for `download` / `models` / `setup`.
    pub links: &'static [(&'static str, &'static str, &'static str)],
    pub subscription: bool,
    pub hide_advanced: bool,
    pub disabled: bool,
    pub built_in: bool,
    pub checks_availability: bool,
}

impl Provider {
    /// `getRequiredConfigFields`
    pub fn required_fields(&self) -> Vec<&'static str> {
        self.requirements
            .iter()
            .flat_map(|requirement| match requirement {
                Requirement::Config(fields) => fields.to_vec(),
                _ => Vec::new(),
            })
            .collect()
    }
}

pub static STT_PROVIDERS: &[Provider] = &[
    Provider {
        id: "anarlog",
        display_name: "Anarlog",
        badge: Some("Recommended"),
        description: None,
        icon: Icon::Image("anarlog-icon.png"),
        base_url: None,
        base_url_is_api: true,
        models: &["cloud"],
        requirements: &[],
        links: &[],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: true,
        checks_availability: false,
    },
    Provider {
        id: "soniqo",
        display_name: "Soniqo",
        badge: Some("On device"),
        description: None,
        icon: Icon::Glyph("waveform"),
        base_url: Some(""),
        base_url_is_api: false,
        models: &[],
        requirements: &[],
        links: &[],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: true,
        checks_availability: false,
    },
    Provider {
        id: "apple_speech",
        display_name: "Apple Speech",
        badge: Some("On device"),
        description: None,
        icon: Icon::Mono("brands/apple.svg", None),
        base_url: Some(""),
        base_url_is_api: false,
        models: &[],
        requirements: &[],
        links: &[],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: true,
        checks_availability: false,
    },
    Provider {
        id: "local_file",
        display_name: "BYO-model",
        badge: Some("On device"),
        description: None,
        icon: Icon::Glyph("cpu"),
        base_url: Some(""),
        base_url_is_api: false,
        models: &["local-file"],
        requirements: &[],
        links: &[],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: true,
        checks_availability: false,
    },
    Provider {
        id: "deepgram",
        display_name: "Deepgram",
        badge: None,
        description: None,
        icon: Icon::Image("brands/deepgram.svg"),
        base_url: Some("https://api.deepgram.com/v1"),
        base_url_is_api: false,
        models: &[
            "flux-general-multi",
            "flux-general-en",
            "nova-3-general",
            "nova-3-medical",
        ],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://developers.deepgram.com/docs/models-languages-overview",
            ),
            ("setup", "API setup", "https://console.deepgram.com/"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "assemblyai",
        display_name: "AssemblyAI",
        badge: None,
        description: None,
        icon: Icon::Image("brands/assemblyai.svg"),
        base_url: Some("https://api.assemblyai.com"),
        base_url_is_api: false,
        models: &["universal-3-5-pro", "universal-3-5-pro-realtime"],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://www.assemblyai.com/docs/speech-to-text",
            ),
            ("setup", "API setup", "https://www.assemblyai.com/dashboard"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "openai",
        display_name: "OpenAI",
        badge: None,
        description: None,
        icon: Icon::Mono("brands/openai.svg", None),
        base_url: Some("https://api.openai.com/v1"),
        base_url_is_api: false,
        models: &[
            "gpt-live-transcribe",
            "gpt-transcribe",
            "gpt-4o-transcribe-diarize",
            "whisper-1",
        ],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://platform.openai.com/docs/guides/speech-to-text",
            ),
            ("setup", "API setup", "https://platform.openai.com/api-keys"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "openrouter",
        display_name: "OpenRouter",
        badge: Some("After recording"),
        description: None,
        icon: Icon::Mono("brands/openrouter.svg", Some(0x6566F1)),
        base_url: Some("https://openrouter.ai/api/v1"),
        base_url_is_api: false,
        models: &[
            "openai/gpt-transcribe",
            "mistralai/voxtral-mini-transcribe",
            "openai/whisper-large-v3-turbo",
            "openai/whisper-large-v3",
            "fish-audio/transcribe-1",
            "x-ai/grok-stt-1.0",
            "deepgram/nova-3",
            "microsoft/mai-transcribe-1.5",
            "nvidia/parakeet-tdt-0.6b-v3",
            "qwen/qwen3-asr-flash-2026-02-10",
            "qwen/qwen3-asr-1.7b",
            "qwen/qwen3-asr-0.6b",
            "nvidia/nemotron-3.5-asr-streaming-multilingual-0.6b",
            "mistralai/voxtral-small-24b-2507-stt",
            "mistralai/voxtral-mini-3b-2507",
            "google/chirp-3",
            "openai/whisper-1",
        ],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://openrouter.ai/models?output_modalities=transcription",
            ),
            ("setup", "API setup", "https://openrouter.ai/settings/keys"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "dashscope",
        display_name: "Alibaba Cloud Model Studio",
        badge: None,
        description: None,
        icon: Icon::Image("brands/alibaba-cloud.svg"),
        base_url: Some("https://dashscope-intl.aliyuncs.com"),
        base_url_is_api: false,
        models: &[
            "qwen3-asr-flash-realtime",
            "qwen3-asr-flash-realtime-2026-02-10",
        ],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://www.alibabacloud.com/help/en/model-studio/real-time-speech-recognition-user-guide",
            ),
            (
                "setup",
                "API setup",
                "https://www.alibabacloud.com/help/en/model-studio/get-api-key",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "zai",
        display_name: "Z.AI",
        badge: Some("After recording"),
        description: None,
        icon: Icon::Mono("brands/zai.svg", None),
        base_url: Some("https://api.z.ai/api/paas/v4"),
        base_url_is_api: false,
        models: &["glm-asr-2512"],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://docs.z.ai/guides/audio/glm-asr-2512",
            ),
            (
                "setup",
                "API setup",
                "https://docs.z.ai/api-reference/introduction",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "siliconflow",
        display_name: "SiliconFlow",
        badge: Some("After recording"),
        description: None,
        icon: Icon::Image("brands/siliconcloud.svg"),
        base_url: Some("https://api.siliconflow.com/v1"),
        base_url_is_api: false,
        models: &["FunAudioLLM/SenseVoiceSmall", "TeleAI/TeleSpeechASR"],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://docs.siliconflow.com/en/api-reference/audio/create-audio-transcriptions",
            ),
            (
                "setup",
                "API setup",
                "https://docs.siliconflow.com/en/userguide/quickstart",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "google_generative_ai",
        display_name: "Google Gemini",
        badge: None,
        description: None,
        icon: Icon::Mono("brands/gemini.svg", None),
        base_url: Some("https://generativelanguage.googleapis.com/v1beta"),
        base_url_is_api: false,
        models: &["gemini-3.5-transcribe-live", "gemini-3.5-transcribe"],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://ai.google.dev/gemini-api/docs/models",
            ),
            ("setup", "API setup", "https://aistudio.google.com/api-keys"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "google_cloud",
        display_name: "Google Cloud Speech-to-Text",
        badge: Some("Short batch"),
        description: None,
        icon: Icon::Image("brands/google-cloud.svg"),
        base_url: Some("https://speech.googleapis.com/v1"),
        base_url_is_api: false,
        models: &["latest_long"],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://cloud.google.com/speech-to-text/docs/transcription-model",
            ),
            (
                "setup",
                "API setup",
                "https://cloud.google.com/speech-to-text/docs/authentication",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "aws_transcribe",
        display_name: "Amazon Transcribe",
        badge: Some("Gateway"),
        description: None,
        icon: Icon::Image("brands/aws.svg"),
        base_url: None,
        base_url_is_api: false,
        models: &["amazon-transcribe"],
        requirements: &[Requirement::Config(&["base_url", "api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://docs.aws.amazon.com/transcribe/latest/dg/how-it-works.html",
            ),
            (
                "setup",
                "API setup",
                "https://docs.aws.amazon.com/transcribe/latest/dg/getting-started-http-websocket.html",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "azure_speech",
        display_name: "Azure AI Speech",
        badge: Some("After recording"),
        description: None,
        icon: Icon::Mono("brands/azure.svg", None),
        base_url: None,
        base_url_is_api: false,
        models: &["fast-transcription"],
        requirements: &[Requirement::Config(&["base_url", "api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://learn.microsoft.com/azure/ai-services/speech-service/fast-transcription-create",
            ),
            (
                "setup",
                "API setup",
                "https://learn.microsoft.com/azure/ai-services/speech-service/get-started-speech-to-text",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "elevenlabs",
        display_name: "ElevenLabs",
        badge: None,
        description: None,
        icon: Icon::Mono("brands/elevenlabs.svg", None),
        base_url: Some("https://api.elevenlabs.io"),
        base_url_is_api: false,
        models: &["scribe_v2", "scribe_v2_realtime"],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://elevenlabs.io/docs/capabilities/speech-to-text",
            ),
            (
                "setup",
                "API setup",
                "https://elevenlabs.io/app/settings/api-keys",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "soniox",
        display_name: "Soniox",
        badge: None,
        description: None,
        icon: Icon::Image("brands/soniox-black.png"),
        base_url: Some("https://api.soniox.com"),
        base_url_is_api: false,
        models: &["stt-rt-v5"],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://soniox.com/docs/stt/models",
            ),
            ("setup", "API setup", "https://console.soniox.com/"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "meta",
        display_name: "Meta Muse",
        badge: None,
        description: None,
        icon: Icon::Image("model-icons/meta-logo.svg"),
        base_url: Some("https://api.meta.ai/v1"),
        base_url_is_api: false,
        models: &["muse-voice-transcribe-1.0"],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://dev.meta.ai/docs/speech-to-text",
            ),
            ("setup", "API setup", "https://dev.meta.ai/"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "speechmatics",
        display_name: "Speechmatics",
        badge: Some("After recording"),
        description: None,
        icon: Icon::Image("brands/speechmatics.svg"),
        base_url: Some("https://eu1.asr.api.speechmatics.com/v2"),
        base_url_is_api: false,
        models: &["enhanced", "standard"],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://docs.speechmatics.com/speech-to-text/batch/quickstart",
            ),
            (
                "setup",
                "API setup",
                "https://portal.speechmatics.com/settings/api-keys",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "groq",
        display_name: "Groq",
        badge: Some("After recording"),
        description: None,
        icon: Icon::Mono("brands/groq.svg", Some(0xF55036)),
        base_url: Some("https://api.groq.com/openai/v1"),
        base_url_is_api: false,
        models: &["whisper-large-v3-turbo", "whisper-large-v3"],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://console.groq.com/docs/speech-to-text",
            ),
            ("setup", "API setup", "https://console.groq.com/keys"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "mistral",
        display_name: "Mistral",
        badge: None,
        description: None,
        icon: Icon::Image("brands/mistral.svg"),
        base_url: Some("https://api.mistral.ai/v1"),
        base_url_is_api: false,
        models: &["voxtral-mini-2602", "voxtral-mini-transcribe-realtime-2602"],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://docs.mistral.ai/capabilities/audio/",
            ),
            ("setup", "API setup", "https://console.mistral.ai/api-keys"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "revai",
        display_name: "Rev AI",
        badge: Some("After recording"),
        description: None,
        icon: Icon::Image("brands/revai.svg"),
        base_url: Some("https://api.rev.ai/speechtotext/v1"),
        base_url_is_api: false,
        models: &["machine"],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://docs.rev.ai/api/asynchronous/get-started",
            ),
            ("setup", "API setup", "https://www.rev.ai/access_token"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "gladia",
        display_name: "Gladia",
        badge: None,
        description: None,
        icon: Icon::Image("brands/gladia.svg"),
        base_url: Some("https://api.gladia.io"),
        base_url_is_api: false,
        models: &["solaria-3", "solaria-1"],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            ("models", "Available models", "https://docs.gladia.io/"),
            ("setup", "API setup", "https://app.gladia.io/"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "cartesia",
        display_name: "Cartesia",
        badge: None,
        description: None,
        icon: Icon::Image("brands/cartesia.svg"),
        base_url: Some("https://api.cartesia.ai"),
        base_url_is_api: false,
        models: &["ink-2"],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://docs.cartesia.ai/api-reference/stt/transcribe",
            ),
            ("setup", "API setup", "https://play.cartesia.ai/keys"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "cloudflare_workers_ai",
        display_name: "Cloudflare Workers AI",
        badge: None,
        description: None,
        icon: Icon::Image("brands/cloudflare.svg"),
        base_url: None,
        base_url_is_api: false,
        models: &["nova-3"],
        requirements: &[Requirement::Config(&["base_url", "api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://developers.cloudflare.com/workers-ai/models/nova-3/",
            ),
            (
                "setup",
                "API setup",
                "https://developers.cloudflare.com/workers-ai/",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "together",
        display_name: "Together AI",
        badge: Some("After recording"),
        description: None,
        icon: Icon::Image("brands/together.svg"),
        base_url: Some("https://api.together.xyz/v1"),
        base_url_is_api: false,
        models: &[
            "openai/whisper-large-v3",
            "nvidia/parakeet-tdt-0.6b-v3",
            "nvidia/nemotron-3.5-asr-streaming-0.6b",
            "nvidia/nemotron-3-asr-streaming-0.6b",
        ],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://docs.together.ai/docs/inference/transcription/overview",
            ),
            (
                "setup",
                "API setup",
                "https://api.together.ai/settings/api-keys",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "xai",
        display_name: "xAI",
        badge: None,
        description: None,
        icon: Icon::Mono("brands/xai.svg", None),
        base_url: Some("https://api.x.ai/v1"),
        base_url_is_api: false,
        models: &["xai-stt"],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://docs.x.ai/developers/model-capabilities/audio/speech-to-text",
            ),
            ("setup", "API setup", "https://console.x.ai/"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "smallestai",
        display_name: "Smallest AI",
        badge: None,
        description: None,
        icon: Icon::Image("brands/smallestai.svg"),
        base_url: Some("https://api.smallest.ai"),
        base_url_is_api: false,
        models: &["pulse", "pulse-pro"],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://docs.smallest.ai/models/documentation/speech-to-text-pulse/overview",
            ),
            (
                "setup",
                "API setup",
                "https://app.smallest.ai/dashboard/api-keys",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "pyannote",
        display_name: "pyannoteAI",
        badge: Some("After recording"),
        description: None,
        icon: Icon::Image("brands/pyannote-logo-black.png"),
        base_url: Some("https://api.pyannote.ai"),
        base_url_is_api: false,
        models: &["parakeet-tdt-0.6b-v3", "faster-whisper-large-v3-turbo"],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            ("models", "Available models", "https://docs.pyannote.ai/"),
            ("setup", "API setup", "https://dashboard.pyannote.ai/"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "cohere",
        display_name: "Cohere",
        badge: Some("After recording"),
        description: None,
        icon: Icon::Image("brands/cohere.svg"),
        base_url: Some("https://api.cohere.com/v2"),
        base_url_is_api: false,
        models: &[
            "cohere-transcribe-03-2026",
            "cohere-transcribe-arabic-07-2026",
        ],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://docs.cohere.com/docs/transcribe",
            ),
            (
                "setup",
                "API setup",
                "https://dashboard.cohere.com/api-keys",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "aquavoice",
        display_name: "AquaVoice",
        badge: Some("After recording"),
        description: None,
        icon: Icon::Image("brands/aquavoice-black.png"),
        base_url: Some("https://api.aquavoice.com/v1"),
        base_url_is_api: false,
        models: &["avalon-v1.5"],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://aquavoice.com/avalon-api/docs",
            ),
            (
                "setup",
                "API setup",
                "https://app.aquavoice.com/api-dashboard",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "custom",
        display_name: "Custom",
        badge: None,
        description: Some("Deepgram-compatible"),
        icon: Icon::Glyph("shuffle"),
        base_url: None,
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["base_url", "api_key"])],
        links: &[],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
];

pub static LLM_PROVIDERS: &[Provider] = &[
    Provider {
        id: "anarlog",
        display_name: "Anarlog",
        badge: Some("Recommended"),
        description: None,
        icon: Icon::Image("anarlog-icon.png"),
        base_url: None,
        base_url_is_api: true,
        models: &[],
        requirements: &[Requirement::Auth, Requirement::Entitlement("pro")],
        links: &[],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "claude",
        display_name: "Claude",
        badge: Some("Subscription"),
        description: None,
        icon: Icon::Mono("brands/anthropic.svg", None),
        base_url: Some("https://api.anthropic.com/v1"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[("setup", "Claude Pro / Max", "https://claude.ai/upgrade")],
        subscription: true,
        hide_advanced: true,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "chatgpt",
        display_name: "ChatGPT",
        badge: Some("Subscription"),
        description: None,
        icon: Icon::Mono("brands/openai.svg", None),
        base_url: Some("https://chatgpt.com/backend-api/codex"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[("setup", "ChatGPT plans", "https://chatgpt.com/")],
        subscription: true,
        hide_advanced: true,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "grok",
        display_name: "Grok",
        badge: Some("Subscription"),
        description: None,
        icon: Icon::Mono("brands/xai.svg", None),
        base_url: Some("https://api.x.ai/v1"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[("setup", "SuperGrok", "https://grok.com/")],
        subscription: true,
        hide_advanced: true,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "github_copilot",
        display_name: "GitHub Copilot",
        badge: Some("Subscription"),
        description: None,
        icon: Icon::Mono("brands/github-copilot.svg", None),
        base_url: Some("https://api.githubcopilot.com"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[(
            "setup",
            "GitHub Copilot",
            "https://github.com/features/copilot",
        )],
        subscription: true,
        hide_advanced: true,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "kimi_code",
        display_name: "Kimi Code",
        badge: Some("Subscription"),
        description: None,
        icon: Icon::Mono("brands/moonshot.svg", None),
        base_url: Some("https://api.kimi.com/coding/v1"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[(
            "setup",
            "Kimi Code membership",
            "https://www.kimi.com/en/help/kimi-code/membership-guide",
        )],
        subscription: true,
        hide_advanced: true,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "openai",
        display_name: "OpenAI",
        badge: None,
        description: None,
        icon: Icon::Mono("brands/openai.svg", None),
        base_url: Some("https://api.openai.com/v1"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://platform.openai.com/docs/models",
            ),
            ("setup", "API setup", "https://platform.openai.com/api-keys"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "anthropic",
        display_name: "Anthropic",
        badge: None,
        description: None,
        icon: Icon::Mono("brands/anthropic.svg", None),
        base_url: Some("https://api.anthropic.com/v1"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://docs.anthropic.com/en/docs/about-claude/models",
            ),
            (
                "setup",
                "API setup",
                "https://console.anthropic.com/settings/keys",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "google_generative_ai",
        display_name: "Google Gemini",
        badge: None,
        description: None,
        icon: Icon::Mono("brands/gemini.svg", None),
        base_url: Some("https://generativelanguage.googleapis.com/v1beta"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://ai.google.dev/gemini-api/docs/models",
            ),
            ("setup", "API setup", "https://aistudio.google.com/api-keys"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "openrouter",
        display_name: "OpenRouter",
        badge: None,
        description: None,
        icon: Icon::Mono("brands/openrouter.svg", Some(0x6566F1)),
        base_url: Some("https://openrouter.ai/api/v1"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            ("models", "Available models", "https://openrouter.ai/models"),
            ("setup", "API setup", "https://openrouter.ai/settings/keys"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "moonshot",
        display_name: "Moonshot AI",
        badge: None,
        description: None,
        icon: Icon::Mono("brands/moonshot.svg", None),
        base_url: Some("https://api.moonshot.ai/v1"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://platform.kimi.ai/docs/api/list-models",
            ),
            (
                "setup",
                "API setup",
                "https://platform.kimi.ai/docs/overview",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "zai",
        display_name: "Z.AI",
        badge: None,
        description: None,
        icon: Icon::Mono("brands/zai.svg", None),
        base_url: Some("https://api.z.ai/api/paas/v4"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://docs.z.ai/guides/overview/overview",
            ),
            (
                "setup",
                "API setup",
                "https://docs.z.ai/api-reference/introduction",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "deepseek",
        display_name: "DeepSeek",
        badge: None,
        description: None,
        icon: Icon::Image("brands/deepseek.svg"),
        base_url: Some("https://api.deepseek.com"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://api-docs.deepseek.com/quick_start/pricing",
            ),
            (
                "setup",
                "API setup",
                "https://platform.deepseek.com/api_keys",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "alibaba_cloud",
        display_name: "Alibaba Cloud Model Studio",
        badge: None,
        description: None,
        icon: Icon::Image("brands/alibaba-cloud.svg"),
        base_url: Some("https://dashscope-intl.aliyuncs.com/compatible-mode/v1"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://www.alibabacloud.com/help/en/model-studio/getting-started/models",
            ),
            (
                "setup",
                "API setup",
                "https://www.alibabacloud.com/help/en/model-studio/base-url",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "siliconflow",
        display_name: "SiliconFlow",
        badge: None,
        description: None,
        icon: Icon::Image("brands/siliconcloud.svg"),
        base_url: Some("https://api.siliconflow.com/v1"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://docs.siliconflow.com/en/userguide/introduction",
            ),
            (
                "setup",
                "API setup",
                "https://docs.siliconflow.com/en/userguide/quickstart",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "amazon_bedrock",
        display_name: "Amazon Bedrock",
        badge: None,
        description: None,
        icon: Icon::Image("brands/aws.svg"),
        base_url: None,
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["base_url", "api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html",
            ),
            (
                "setup",
                "API setup",
                "https://docs.aws.amazon.com/bedrock/latest/userguide/bedrock-mantle.html",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "azure_openai",
        display_name: "Azure OpenAI",
        badge: None,
        description: None,
        icon: Icon::Mono("brands/azure.svg", None),
        base_url: None,
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["base_url", "api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://learn.microsoft.com/azure/ai-foundry/openai/concepts/models",
            ),
            (
                "setup",
                "API setup",
                "https://learn.microsoft.com/azure/ai-foundry/openai/how-to/create-resource",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "google_vertex_ai",
        display_name: "Google Vertex AI",
        badge: None,
        description: None,
        icon: Icon::Image("brands/google-cloud.svg"),
        base_url: None,
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["base_url", "api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models",
            ),
            (
                "setup",
                "API setup",
                "https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/call-vertex-using-openai-library",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "azure_ai",
        display_name: "Azure AI Foundry",
        badge: None,
        description: None,
        icon: Icon::Mono("brands/azure-ai.svg", None),
        base_url: None,
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["base_url", "api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://learn.microsoft.com/azure/ai-foundry/how-to/model-catalog-overview",
            ),
            ("setup", "API setup", "https://ai.azure.com/"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "groq",
        display_name: "Groq",
        badge: None,
        description: None,
        icon: Icon::Mono("brands/groq.svg", Some(0xF55036)),
        base_url: Some("https://api.groq.com/openai/v1"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://console.groq.com/docs/models",
            ),
            ("setup", "API setup", "https://console.groq.com/keys"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "ollama",
        display_name: "Ollama",
        badge: None,
        description: None,
        icon: Icon::Mono("brands/ollama.svg", None),
        base_url: Some("http://127.0.0.1:11434/v1"),
        base_url_is_api: false,
        models: &[],
        requirements: &[],
        links: &[
            ("download", "Download Ollama", "https://ollama.com/download"),
            ("models", "Available models", "https://ollama.com/library"),
            (
                "setup",
                "Setup guide",
                "https://docs.anarlog.so/ai-setup#ollama",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: true,
    },
    Provider {
        id: "xai",
        display_name: "xAI",
        badge: None,
        description: None,
        icon: Icon::Mono("brands/xai.svg", None),
        base_url: Some("https://api.x.ai/v1"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://docs.x.ai/developers/models",
            ),
            ("setup", "API setup", "https://console.x.ai/"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "mistral",
        display_name: "Mistral",
        badge: None,
        description: None,
        icon: Icon::Image("brands/mistral.svg"),
        base_url: Some("https://api.mistral.ai/v1"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://docs.mistral.ai/getting-started/models/",
            ),
            ("setup", "API setup", "https://console.mistral.ai/api-keys"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "meta",
        display_name: "Meta Muse",
        badge: None,
        description: None,
        icon: Icon::Image("model-icons/meta-logo.svg"),
        base_url: Some("https://api.meta.ai/v1"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://dev.meta.ai/docs/models",
            ),
            ("setup", "API setup", "https://dev.meta.ai/"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "together",
        display_name: "Together AI",
        badge: None,
        description: None,
        icon: Icon::Image("brands/together.svg"),
        base_url: Some("https://api.together.xyz/v1"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://docs.together.ai/docs/serverless-models",
            ),
            (
                "setup",
                "API setup",
                "https://api.together.ai/settings/api-keys",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "cohere",
        display_name: "Cohere",
        badge: None,
        description: None,
        icon: Icon::Image("brands/cohere.svg"),
        base_url: Some("https://api.cohere.ai/compatibility/v1"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://docs.cohere.com/docs/models",
            ),
            (
                "setup",
                "API setup",
                "https://docs.cohere.com/docs/compatibility-api",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "fireworks",
        display_name: "Fireworks AI",
        badge: None,
        description: None,
        icon: Icon::Image("brands/fireworks.svg"),
        base_url: Some("https://api.fireworks.ai/inference/v1"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            ("models", "Available models", "https://fireworks.ai/models"),
            (
                "setup",
                "API setup",
                "https://fireworks.ai/account/api-keys",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "cloudflare_workers_ai",
        display_name: "Cloudflare Workers AI",
        badge: None,
        description: None,
        icon: Icon::Image("brands/cloudflare.svg"),
        base_url: None,
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["base_url", "api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://developers.cloudflare.com/workers-ai/models/",
            ),
            (
                "setup",
                "API setup",
                "https://developers.cloudflare.com/workers-ai/configuration/open-ai-compatibility/",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "cerebras",
        display_name: "Cerebras",
        badge: None,
        description: None,
        icon: Icon::Image("brands/cerebras.svg"),
        base_url: Some("https://api.cerebras.ai/v1"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "models",
                "Available models",
                "https://inference-docs.cerebras.ai/models/overview",
            ),
            ("setup", "API setup", "https://cloud.cerebras.ai/"),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
    Provider {
        id: "lmstudio",
        display_name: "LM Studio",
        badge: None,
        description: None,
        icon: Icon::Mono("brands/lmstudio.svg", Some(0x4338CA)),
        base_url: Some("http://127.0.0.1:1234/v1"),
        base_url_is_api: false,
        models: &[],
        requirements: &[],
        links: &[
            (
                "download",
                "Download LM Studio",
                "https://lmstudio.ai/download",
            ),
            ("models", "Available models", "https://lmstudio.ai/models"),
            (
                "setup",
                "Setup guide",
                "https://docs.anarlog.so/ai-setup#lm-studio",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: true,
    },
    Provider {
        id: "unsloth",
        display_name: "Unsloth",
        badge: None,
        description: None,
        icon: Icon::Image("brands/unsloth.png"),
        base_url: Some("http://127.0.0.1:8888/v1"),
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["api_key"])],
        links: &[
            (
                "download",
                "Download Unsloth",
                "https://unsloth.ai/docs/desktop",
            ),
            (
                "models",
                "Available models",
                "https://huggingface.co/unsloth",
            ),
            (
                "setup",
                "Setup guide",
                "https://docs.anarlog.so/ai-setup#unsloth",
            ),
        ],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: true,
    },
    Provider {
        id: "apple_foundation",
        display_name: "Apple Intelligence",
        badge: None,
        description: None,
        icon: Icon::Mono("brands/apple.svg", None),
        base_url: None,
        base_url_is_api: false,
        models: &[],
        requirements: &[],
        links: &[],
        subscription: false,
        hide_advanced: true,
        disabled: false,
        built_in: false,
        checks_availability: true,
    },
    Provider {
        id: "custom",
        display_name: "Custom",
        badge: None,
        description: None,
        icon: Icon::Glyph("shuffle"),
        base_url: None,
        base_url_is_api: false,
        models: &[],
        requirements: &[Requirement::Config(&["base_url", "api_key"])],
        links: &[],
        subscription: false,
        hide_advanced: false,
        disabled: false,
        built_in: false,
        checks_availability: false,
    },
];
