use std::borrow::Cow;

use gpui::{AssetSource, SharedString};

/// Icons are the Hugeicons (MIT) glyphs the Tauri app maps in
/// `packages/ui/src/components/icons.tsx`; brand images come from
/// `apps/desktop/public/assets`. Embedded so the binary is self-contained.
/// `TEMPLATE_ICON_COMPONENTS` keys and their embedded assets, in the
/// registry order the picker shows.
pub const TEMPLATE_ICON_ASSETS: &[(&str, &str)] = &[
    ("activity", "tpl-activity"),
    ("bar-chart", "tpl-bar-chart"),
    ("bell", "tpl-bell"),
    ("book-open", "tpl-book-open"),
    ("brain", "tpl-brain"),
    ("briefcase", "tpl-briefcase"),
    ("bug", "tpl-bug"),
    ("building", "tpl-building"),
    ("calendar", "tpl-calendar"),
    ("camera", "tpl-camera"),
    ("chart", "tpl-chart"),
    ("alert", "tpl-alert"),
    ("clipboard-check", "tpl-clipboard-check"),
    ("clock", "tpl-clock"),
    ("cloud", "tpl-cloud"),
    ("code", "tpl-code"),
    ("coffee", "tpl-coffee"),
    ("compass", "tpl-compass"),
    ("credit-card", "tpl-credit-card"),
    ("crown", "tpl-crown"),
    ("database", "tpl-database"),
    ("dollar", "tpl-dollar"),
    ("file-text", "tpl-file-text"),
    ("flag", "tpl-flag"),
    ("flame", "tpl-flame"),
    ("folder", "tpl-folder"),
    ("globe", "tpl-globe"),
    ("graduation", "tpl-graduation"),
    ("hammer", "tpl-hammer"),
    ("handshake", "tpl-handshake"),
    ("headphones", "tpl-headphones"),
    ("heart", "tpl-heart"),
    ("home", "tpl-home"),
    ("image", "tpl-image"),
    ("key", "tpl-key"),
    ("landmark", "tpl-landmark"),
    ("leaf", "tpl-leaf"),
    ("lightbulb", "tpl-lightbulb"),
    ("link", "tpl-link"),
    ("list-checks", "tpl-list-checks"),
    ("lock", "tpl-lock"),
    ("mail", "tpl-mail"),
    ("map", "tpl-map"),
    ("megaphone", "tpl-megaphone"),
    ("message", "tpl-message"),
    ("messages", "tpl-messages"),
    ("mic", "tpl-mic"),
    ("milestone", "tpl-milestone"),
    ("moon", "tpl-moon"),
    ("music", "tpl-music"),
    ("notebook-tabs", "tpl-notebook-tabs"),
    ("package", "tpl-package"),
    ("palette", "tpl-palette"),
    ("paperclip", "tpl-paperclip"),
    ("pen", "tpl-pen"),
    ("phone", "tpl-phone"),
    ("pie-chart", "tpl-pie-chart"),
    ("plane", "tpl-plane"),
    ("presentation", "tpl-presentation"),
    ("puzzle", "tpl-puzzle"),
    ("rocket", "tpl-rocket"),
    ("scale", "tpl-scale"),
    ("search", "tpl-search"),
    ("settings", "tpl-settings"),
    ("shield", "tpl-shield"),
    ("shopping", "tpl-shopping"),
    ("sparkles", "tpl-sparkles"),
    ("kanban", "tpl-kanban"),
    ("star", "tpl-star"),
    ("stethoscope", "tpl-stethoscope"),
    ("sun", "tpl-sun"),
    ("target", "tpl-target"),
    ("trending", "tpl-trending"),
    ("trophy", "tpl-trophy"),
    ("user-search", "tpl-user-search"),
    ("users", "tpl-users"),
    ("video", "tpl-video"),
    ("wrench", "tpl-wrench"),
    ("zap", "tpl-zap"),
];

pub struct Assets;

macro_rules! embedded {
    ($($path:literal),* $(,)?) => {
        const FILES: &[(&str, &[u8])] = &[
            $(($path, include_bytes!(concat!("../assets/", $path))),)*
        ];
    };
}

embedded!(
    "brands/alibaba-cloud.svg",
    "brands/anthropic.svg",
    "brands/apple.svg",
    "brands/aquavoice-black.png",
    "brands/assemblyai.svg",
    "brands/aws.svg",
    "brands/azure-ai.svg",
    "brands/azure.svg",
    "brands/cartesia.svg",
    "brands/cerebras.svg",
    "brands/cloudflare.svg",
    "brands/cohere.svg",
    "brands/deepgram.svg",
    "brands/deepseek.svg",
    "brands/elevenlabs.svg",
    "brands/fireworks.svg",
    "brands/gemini.svg",
    "brands/github-copilot.svg",
    "brands/gladia.svg",
    "brands/google-calendar.svg",
    "brands/google-cloud.svg",
    "brands/groq.svg",
    "brands/linear.svg",
    "brands/linkedin.svg",
    "brands/lmstudio.svg",
    "brands/markdown-mark.svg",
    "brands/mistral.svg",
    "brands/moonshot.svg",
    "brands/notion.svg",
    "brands/ollama.svg",
    "brands/openai.svg",
    "model-icons/meta-logo.svg",
    "model-icons/nvidia-logo.svg",
    "model-icons/openai-logo.svg",
    "model-icons/qwen-logo.svg",
    "brands/openrouter.svg",
    "brands/outlook.svg",
    "brands/pyannote-logo-black.png",
    "brands/revai.svg",
    "brands/siliconcloud.svg",
    "brands/slack.svg",
    "brands/smallestai.svg",
    "brands/soniox-black.png",
    "brands/speechmatics.svg",
    "brands/together.svg",
    "brands/unsloth.png",
    "brands/xai.svg",
    "brands/zai.svg",
    "icons/alert-triangle.svg",
    "icons/app-window.svg",
    "icons/arrow-clockwise.svg",
    "icons/arrow-counter-clockwise.svg",
    "icons/arrow-down.svg",
    "icons/arrow-elbow-down-left.svg",
    "icons/arrow-square-out.svg",
    "icons/arrows-in-simple.svg",
    "icons/arrows-out-simple.svg",
    "icons/arrow-left.svg",
    "icons/arrow-right.svg",
    "icons/arrow-up-right.svg",
    "icons/arrow-up.svg",
    "icons/arrows-clockwise.svg",
    "icons/arrows-down-up.svg",
    "icons/arrows-merge.svg",
    "icons/brain.svg",
    "icons/arrows-counter-clockwise.svg",
    "icons/bell.svg",
    "icons/book-open-text.svg",
    "icons/book-open.svg",
    "icons/buildings.svg",
    "icons/camera.svg",
    "icons/calendar-blank.svg",
    "icons/calendar-dots.svg",
    "icons/calendar.svg",
    "icons/caret-down.svg",
    "icons/caret-left.svg",
    "icons/caret-right.svg",
    "icons/caret-up.svg",
    "icons/cpu.svg",
    "icons/chart-bar.svg",
    "icons/chat-circle.svg",
    "icons/check-circle.svg",
    "icons/check.svg",
    "icons/circle-notch.svg",
    "icons/clock-counter-clockwise.svg",
    "icons/close-x.svg",
    "icons/code.svg",
    "icons/copy.svg",
    "icons/discord-logo.svg",
    "icons/dots-three.svg",
    "icons/download-simple.svg",
    "icons/envelope.svg",
    "icons/external-link.svg",
    "icons/eye.svg",
    "icons/eye-slash.svg",
    "icons/file-arrow-down.svg",
    "icons/file-spreadsheet.svg",
    "icons/file-text.svg",
    "icons/file.svg",
    "icons/filter.svg",
    "icons/filter-bold.svg",
    "icons/floppy-disk.svg",
    "icons/folder-open.svg",
    "icons/folder.svg",
    "icons/gear.svg",
    "icons/github-logo.svg",
    "icons/grip-vertical.svg",
    "icons/headset.svg",
    "icons/heart.svg",
    "icons/heart-bold.svg",
    "icons/highlighter.svg",
    "icons/image.svg",
    "icons/info-circle.svg",
    "icons/lightning.svg",
    "icons/list-checks.svg",
    "icons/lock-key.svg",
    "icons/lock.svg",
    "icons/magic-wand.svg",
    "icons/magnifying-glass.svg",
    "icons/map-pin.svg",
    "icons/microphone-slash.svg",
    "icons/microphone.svg",
    "icons/more-horizontal.svg",
    "icons/note-edit.svg",
    "icons/note.svg",
    "icons/notebook.svg",
    "icons/minus-circle.svg",
    "icons/pause.svg",
    "icons/pencil.svg",
    "icons/pencil-edit.svg",
    "icons/pencil-simple.svg",
    "icons/picture-in-picture.svg",
    "icons/play.svg",
    "icons/plugs-connected.svg",
    "icons/plus.svg",
    "icons/plus-circle.svg",
    "icons/repeat.svg",
    "icons/popover-tail-border.svg",
    "icons/popover-tail.svg",
    "icons/push-pin.svg",
    "icons/push-pin-bold.svg",
    "icons/search.svg",
    "icons/share-network.svg",
    "icons/share.svg",
    "icons/shield-check.svg",
    "icons/shuffle.svg",
    "icons/sidebar-left.svg",
    "icons/sort-ascending.svg",
    "icons/sort-descending.svg",
    "icons/sparkle.svg",
    "icons/speaker-high.svg",
    "icons/speaker-x.svg",
    "icons/square.svg",
    "icons/sun.svg",
    "icons/swap.svg",
    "icons/text-align-left.svg",
    "icons/text-aa.svg",
    "icons/text-bold.svg",
    "icons/text-italic.svg",
    "icons/text-strikethrough.svg",
    "icons/text-underline.svg",
    "icons/textbox.svg",
    "icons/tpl-activity.svg",
    "icons/tpl-alert.svg",
    "icons/tpl-bar-chart.svg",
    "icons/tpl-bell.svg",
    "icons/tpl-book-open.svg",
    "icons/tpl-brain.svg",
    "icons/tpl-briefcase.svg",
    "icons/tpl-bug.svg",
    "icons/tpl-building.svg",
    "icons/tpl-calendar.svg",
    "icons/tpl-camera.svg",
    "icons/tpl-chart.svg",
    "icons/tpl-clipboard-check.svg",
    "icons/tpl-clock.svg",
    "icons/tpl-cloud.svg",
    "icons/tpl-code.svg",
    "icons/tpl-coffee.svg",
    "icons/tpl-compass.svg",
    "icons/tpl-credit-card.svg",
    "icons/tpl-crown.svg",
    "icons/tpl-database.svg",
    "icons/tpl-dollar.svg",
    "icons/tpl-file-text.svg",
    "icons/tpl-flag.svg",
    "icons/tpl-flame.svg",
    "icons/tpl-folder.svg",
    "icons/tpl-globe.svg",
    "icons/tpl-graduation.svg",
    "icons/tpl-hammer.svg",
    "icons/tpl-handshake.svg",
    "icons/tpl-headphones.svg",
    "icons/tpl-heart.svg",
    "icons/tpl-home.svg",
    "icons/tpl-image.svg",
    "icons/tpl-kanban.svg",
    "icons/tpl-key.svg",
    "icons/tpl-landmark.svg",
    "icons/tpl-leaf.svg",
    "icons/tpl-lightbulb.svg",
    "icons/tpl-link.svg",
    "icons/tpl-list-checks.svg",
    "icons/tpl-lock.svg",
    "icons/tpl-mail.svg",
    "icons/tpl-map.svg",
    "icons/tpl-megaphone.svg",
    "icons/tpl-message.svg",
    "icons/tpl-messages.svg",
    "icons/tpl-mic.svg",
    "icons/tpl-milestone.svg",
    "icons/tpl-moon.svg",
    "icons/tpl-music.svg",
    "icons/tpl-notebook-tabs.svg",
    "icons/tpl-package.svg",
    "icons/tpl-palette.svg",
    "icons/tpl-paperclip.svg",
    "icons/tpl-pen.svg",
    "icons/tpl-phone.svg",
    "icons/tpl-pie-chart.svg",
    "icons/tpl-plane.svg",
    "icons/tpl-presentation.svg",
    "icons/tpl-puzzle.svg",
    "icons/tpl-rocket.svg",
    "icons/tpl-scale.svg",
    "icons/tpl-search.svg",
    "icons/tpl-settings.svg",
    "icons/tpl-shield.svg",
    "icons/tpl-shopping.svg",
    "icons/tpl-sparkles.svg",
    "icons/tpl-star.svg",
    "icons/tpl-stethoscope.svg",
    "icons/tpl-sun.svg",
    "icons/tpl-target.svg",
    "icons/tpl-trending.svg",
    "icons/tpl-trophy.svg",
    "icons/tpl-user-search.svg",
    "icons/tpl-users.svg",
    "icons/tpl-video.svg",
    "icons/tpl-wrench.svg",
    "icons/tpl-zap.svg",
    "icons/trash.svg",
    "icons/trophy.svg",
    "icons/user.svg",
    "icons/user-switch.svg",
    "icons/users-three.svg",
    "icons/users.svg",
    "icons/video-camera.svg",
    "icons/view-sidebar-left.svg",
    "icons/warning-circle.svg",
    "icons/audio-lines.svg",
    "icons/textarea-resizer.svg",
    "icons/chart-line-up.svg",
    "icons/filter-fill.svg",
    "icons/waveform.svg",
    "icons/x-logo.svg",
    "icons/wrench.svg",
    "icons/x-circle.svg",
    "icons/x.svg",
    "anarlog-icon.png",
    "onboarding-video.webp",
    "badges/hello.webp",
    "badges/hello-dark.webp",
    "badges/all-set.webp",
    "badges/all-set-dark.webp",
    "badges/first-words.webp",
    "badges/first-words-dark.webp",
    "badges/good-listener.webp",
    "badges/good-listener-dark.webp",
    "badges/memory-keeper.webp",
    "badges/memory-keeper-dark.webp",
    "badges/story-collector.webp",
    "badges/story-collector-dark.webp",
    "badges/living-library.webp",
    "badges/living-library-dark.webp",
    "badges/finding-rhythm.webp",
    "badges/finding-rhythm-dark.webp",
    "badges/familiar-face.webp",
    "badges/familiar-face-dark.webp",
    "google-meet.svg",
    "teams.png",
    "webex.png",
    "zoom-icon.svg",
);

impl AssetSource for Assets {
    fn load(&self, path: &str) -> anyhow::Result<Option<Cow<'static, [u8]>>> {
        Ok(FILES
            .iter()
            .find(|(name, _)| *name == path)
            .map(|(_, bytes)| Cow::Borrowed(*bytes)))
    }

    fn list(&self, path: &str) -> anyhow::Result<Vec<SharedString>> {
        Ok(FILES
            .iter()
            .filter(|(name, _)| name.starts_with(path))
            .map(|(name, _)| SharedString::from(*name))
            .collect())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_embedded_icon_is_an_svg_document() {
        for (name, bytes) in FILES.iter().filter(|(name, _)| name.ends_with(".svg")) {
            let text = std::str::from_utf8(bytes).unwrap();
            assert!(text.starts_with("<svg"), "{name} is not an svg");
        }
        assert!(Assets.load("icons/search.svg").unwrap().is_some());
        assert!(Assets.load("icons/missing.svg").unwrap().is_none());
        assert_eq!(Assets.list("icons/").unwrap().len(), 211);
    }
}
