[package]
name = "crash-reporting"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anlg-user-error = { workspace = true }
dirs = { workspace = true }
regex = { workspace = true }
sentry = { workspace = true, features = ["tracing"] }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
